name: PR Check Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  list-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: List repository contents
        run: ls -la 